# ![Notas de ES2017: Async/Await](https://i.imgur.com/IYaNvE0.png)

### ðŸ‘‰ Ver [todas las notas](https://github.com/undefinedschool/notes)

## Contenido

- [Intro](https://github.com/undefinedschool/notes-es2017-async-await#intro)
- [Async](https://github.com/undefinedschool/notes-es2017-async-await#async)
- [Await](https://github.com/undefinedschool/notes-es2017-async-await#await)
- [Error Handling](https://github.com/undefinedschool/notes-es2017-async-await#error-handling)
- [Reject](https://github.com/undefinedschool/notes-es2017-async-await#reject)

---

## Intro

Una de las principales desventajas de manejar asincrinismo en JavaScript, es que muchas veces resulta algo complejo razonar o seguir el flujo de las diferentes operaciones, principalmente porque estamos mÃ¡s acostumbrados a pensar de forma _sincrÃ³nica_.

Es por esto que en la versiÃ³n [ES2017](https://medium.com/@tmvvr/ecmascript-async-await-to-the-rescue-fc379ff89146) de JavaScript se incorporÃ³ una nueva forma de trabajar con cÃ³digo asincrÃ³nico, `async/await`.

`async/await` nos permite _pausar_ la ejecuciÃ³n de funciones asincrÃ³nicas, para poder _escribir cÃ³digo asincrÃ³nico que se lea como cÃ³digo sincrÃ³nico_, resultando de esta forma, mÃ¡s legible y simple de razonar.

> ðŸ‘‰ `async/await` no deja de ser _sugar syntax_ (es decir, una forma mÃ¡s simple de escribir) sobre [_Promises_](https://github.com/undefinedschool/notes-es6-promises/)

[![Complete Guide to JS Async & Await ES2017/ES8](https://img.youtube.com/vi/krAYA4rvbdA/0.jpg)](https://www.youtube.com/watch?v=krAYA4rvbdA)
> Ver [Complete Guide to JS Async & Await ES2017/ES8](https://www.youtube.com/watch?v=krAYA4rvbdA)

[â†‘ Ir al inicio](https://github.com/undefinedschool/notes-es2017-async-await#contenido)

## Async

> ðŸ‘‰ El operador `async` transforma una funciÃ³n cualquiera en una que retorna una [Promise](https://github.com/undefinedschool/notes-es6-promises). Entonces, al agregar `async` delante de cualquier funciÃ³n, esta pasa automÃ¡ticamente a retornar una promesa al valor original que retornaba antes. 

Por ejemplo, si tenemos

```js
function sum(a, b) {
  return a + b;
}
```

La funciÃ³n `sum` retorna un nÃºmero. Al agregar `async` delante

```js
async function sum(a, b) {
  return a + b;
}
```

la funciÃ³n pasa a retornar una `Promise` a este nÃºmero.

[â†‘ Ir al inicio](https://github.com/undefinedschool/notes-es2017-async-await#contenido)

## Await

> ðŸ‘‰ **El operador `await` le indica a un valor o expresiÃ³n cualquiera que tenga a continuaciÃ³n, que espere a que la [Promise](https://github.com/undefinedschool/notes-es6-promises) se resuelva antes de continuar** (lo que harÃ­amos con el `.then()`) **y extraer su valor ya resuelto**, es decir, **pausa la ejecuciÃ³n de la funciÃ³n `async`**. Cuando se usa junto con la declaraciÃ³n de una variable o constante (`var`, `let` o `const`), asigna la respuesta de la promesa a la variable, en lugar de la promesa en si misma.

ðŸ‘‰ **`await` sÃ³lo puede utilizarse dentro de una funciÃ³n `async`**

Ejemplo usando `fetch`

```js
async function getPost() {
  const response = await fetch('https://jsonplaceholder.typicode.com/posts/5');
  const post = await response.json();
  
  console.log(post);
  return post;
};

getPost();
```

[![The Async Await Episode I Promised](https://img.youtube.com/vi/vn3tm0quoqE/0.jpg)](https://www.youtube.com/watch?v=vn3tm0quoqE)
> Ver [The Async Await Episode I Promised](https://www.youtube.com/watch?v=vn3tm0quoqE)

> ðŸ‘‰ Algo importante de entender es que hablamos de _pausar la ejecuciÃ³n de la funciÃ³n `async`_ pero no de _bloquear_. Async/Await no deja de ser otra forma de escribir Promises, por lo que se trata siempre de cÃ³digo asincrÃ³nico y **no estamos bloqueando el [_Event Loop_](https://github.com/undefinedschool/notes-event-loop/)** 

[â†‘ Ir al inicio](https://github.com/undefinedschool/notes-es2017-async-await#contenido)

## Error Handling

Si miramos el ejemplo anterior, quÃ© pasarÃ­a si por ejemplo el `fetch` falla? No estamos manejando los errores de ninguna forma. Lo mismo sucede con `.json()`.

Como `fetch` retorna una promesa, podrÃ­amos simplemente agregar el `catch()`

```js
async function getPost() {
  const response = await fetch('https://jsonplaceholder.typicode.com/posts/5').catch(console.error);
  const post = await response.json().catch(console.error);
  
  console.log(post);
  return post;
};

getPost();
```

Una mejor alternativa, para no estar mezclando sintaxis de Async/Await con Promises y simplificar el cÃ³digo, es utilizar el [_try/catch_](https://www.youtube.com/watch?v=cFTFtuEQ-10). Este suele ser el patrÃ³n utilizado para el manejo de errores (_error handling_) cuando usamos Async/Await.

La idea es simplemente, mover todo el cÃ³digo que podrÃ­a fallar adentro del `try` y si alguna promesa falla, manejar el error en el `catch`

```js
async function getPost() {
  try {
    const response = await fetch('https://jsonplaceholder.typicode.com/posts/5');
    const post = await response.json();
  
    console.log(post);
    return post;
  } catch (e) {
    console.error(e.message);
  }
};

getPost();
```

[â†‘ Ir al inicio](https://github.com/undefinedschool/notes-es2017-async-await#contenido)

## Reject

> ðŸ‘‰ Una funciÃ³n `async` retorna un valor envuelto en una [Promise](https://github.com/undefinedschool/notes-es6-promises/) resuelta. Si queremos en cambio retornar una promesa rechazada, usamos `throw` dentro de la funciÃ³n

```js
async function rejection() {
  throw 'I'm rejecting this promise...';
}
```

[â†‘ Ir al inicio](https://github.com/undefinedschool/notes-es2017-async-await#contenido)
